package com.letv.base;
import com.letv.cases.common.*;

public class AppName extends com.letv.cases.common.AppName{
    public static final String LETVREMOTETEST = "Letv自动化测试";
    public static final String PHONE = "电话|Phone";
    public static final String MESSAGE = "信息|Messages";
    public static final String BROWSER = "浏览器|Browser";
    public static final String CAMERA = "相机|Camera";
    public static final String CLOCK = "时钟|Clock";
    public static final String CALENDAR = "日历|Calendar";
    public static final String WEATHER = "天气|Weather";
    public static final String MUSIC = "音乐|Music";
    public static final String TVCONTROLLER = "遥控|Remote control|Remote Control";
    public static final String APPSTORE = "应用商店|Le App|Le Store|LeStore";
    public static final String LETVVIDEO = "乐视视频|Le|Letv";
    public static final String SETTING = "设置|Settings";
    public static final String FILEMANAGER = "文件管理|File management|File manager|File Manager";
    public static final String WALLPAPER = "壁纸|Wallpaper";
    public static final String GALLERY = "图库|Gallery";
    public static final String EMAIL = "电子邮件|Email";
    public static final String CONTACT = "联系人|Contacts";
    public static final String UPGRADE = "系统更新|System update";
    public static final String DOWNLOAD = "下载|Downloads";
    public static final String FEEDBACK = "问题反馈|Feedback";
    public static final String RECORDER = "录音机|Recorder";
    public static final String MAP = "高德地图|Amap";
    public static final String NOTE = "便签|Notes";
    public static final String SYSTEMTOOL = "系统工具|System tools";
    public static final String WPS = "WPS Office|WPS Office";
    public static final String LESTORE = "乐视商城|LetvShop|LeMall";
    public static final String LEACCOUNT = "我的|My Letv";
    public static final String CALCULATOR = "计算器|Calculator";
    public static final String VIDEOPLAYER = "播放器|Player";
    public static final String SIMCARD = "SIM卡应用|SIM Toolkit";
    public static final String LESPORT = "乐视体育|Le Sports";
    public static final String SUPERMANAGER= "管家|Super Manager|Super manager|超级管家|Phone Manager";
    public static final String SUPERSEARCH= "超级搜索";
    public static final String GAMECENTER = "游戏中心|Game Center";
    public static final String LEAUTO = "乐视车联";
    public static final String LEFANBBS = "乐迷社区|乐迷";
    public static final String WEIBO = "微博|Weibo";
    public static final String WECHAT = "微信|WeChat";
    public static final String TODAYNEWS = "今日头条";
    public static final String READER = "阅读|Reader";
    public static final String FANNATION = "生态圈|FanNation";
    public static final String EDAO = "易到";
    public static final String LianMeng = "淘宝联盟";
    public static final String Webchat = "微信";
}
